### PR TITLE
cargo: specify rust-version

### PR DESCRIPTION
**Pull request by xtqqczze**
- specify Rust 1.82 as this is the actual MSRV
- define a workspace
- fix utils clippy lints

### CODE REVIEW

**Comment by xtqqczze** [comment]
This is the error with Rust 1.81:

```log
error[E0658]: precise captures on `impl Trait` are experimental
  --> src/lookup.rs:17:77
   |
17 | pub fn lookup_host(host: &str) -> io::Result<impl Iterator<Item = IpAddr> + use<>> {
   |                                                                             ^^^
   |
   = note: see issue #123432 <https://github.com/rust-lang/rust/issues/123432> for more information

For more information about this error, try `rustc --explain E0658`.
```

MSRV might have been 1.74 but for this error.

**Comment by keeperofdakeys** [comment]
Thanks looks good. I'll push this out as 4.0, since there is another breaking change I'm pushing in #43.

**Comment by xtqqczze** [comment]
Technically, this PR is not a breaking change, it is just codifying the existing MSRV.

For 4.0, you may wish to consider a small breaking change to lower MSRV to 1.70: https://github.com/keeperofdakeys/dns-lookup/pull/47
